
const EVENT_TARGET_BUNDLE = {};

const CALL_FINISHED = new EventTarget();
const FILTER_FINISHED = new EventTarget();
const DATA_HANDLER_FINISHED = new EventTarget();

EVENT_TARGET_BUNDLE.CALL_FINISHED = CALL_FINISHED;
EVENT_TARGET_BUNDLE.FILTER_FINISHED = FILTER_FINISHED;
EVENT_TARGET_BUNDLE.DATA_HANDLER_FINISHED = DATA_HANDLER_FINISHED;


module.exports =  EVENT_TARGET_BUNDLE